### ISSUE TITLE
Not Showing anything when i select my wifi adapter

### ISSUE THREAD

**Issue by starkchaudhary** [davidbombal/red-python-scripts#11]
HII in this it is not showing me anything when i run this command
 how can i fix it while wifite is working

**Comment by davidbombal** [comment]
@starkchaudhary can you please let me know which Wifi Adapter you're running? Please confirm that it supports monitoring and injection mode - see this video: https://youtu.be/UA-IJ8DWh_8

**Comment by davidbombal** [comment]
Haven't heard back from the the person who logged the issue. Am now closing the issue.
