### ISSUE TITLE
wifidos.py help needed

### ISSUE THREAD

**Issue by johnfbrown2000** [davidbombal/red-python-scripts#12]
hi
   i am having the same problem when i run program it says scanning but no ap are seen can you advise thank you john

**Comment by davidbombal** [comment]
Hi John, can you please let me know which WiFi adapter you're using? Also please see this video https://youtu.be/UA-IJ8DWh_8 and confirm that your adapter supports monitor mode and injection.

**Comment by FromMun** [comment]
Hi everybody, it seems like not every adapted is renaming itself to "wlanxmon". My AWUS036ACH  kept original name after enabling monitoring mode. I removed every + "mon" part in script and that fixed my issue.

**Comment by davidbombal** [comment]
@FromMun will be uploading a new script that doesn't use airmon-ng to set the adapter in monitor mode, and it should then always keep the same name.
