### ISSUE TITLE
No networks were found

### ISSUE THREAD

**Issue by AbdallahEghnaim** [davidbombal/red-python-scripts#15]
I ran the first and the second script and the issue is the same both times. 
There were no networks found. I made sure my adapter was in monitor mode. It Just keeps search with no results until I control+C

**Comment by r0anx** [comment]
May be , there's a problem with your wifi adapter.

**Comment by r0anx** [comment]
> I ran the first and the second script and the issue is the same both times. 
> There were no networks found. I made sure my adapter was in monitor mode. It Just keeps search with no results until I control+C
> 
> 
May be , there's a problem with your wifi adapter.

**Comment by davidbombal** [comment]
> I ran the first and the second script and the issue is the same both times.
> There were no networks found. I made sure my adapter was in monitor mode. It Just keeps search with no results until I control+C

Which wifi adapter are you using?

**Comment by Mr-Hacker-07-devil** [comment]
The wifi password using python we previously connected or not...???
