### ISSUE TITLE
Error line 9

### ISSUE THREAD

**Issue by Haitham1983** [davidbombal/red-python-scripts#23]
Hello 
I get this error msg when i try to run script. 

Import csv 
IndentationERROR ; unexpected indent. 

Thanks

**Comment by bener07** [comment]
Hi, the issue can be because of a line try to watch a little bit better the line 9, ir can be because of an desnecessary Space try to resolve it by reading this article https://stackoverflow.com/questions/1016814/what-to-do-with-unexpected-indent-in-python on stackoverflow
