### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by EroxMC** [davidbombal/red-python-scripts#3]
Hey, i have a problems for all theses files and this problem do that they don't works.

Can you fix that ? Thanks.

![Screenshot_4](https://user-images.githubusercontent.com/77900688/106368197-32711900-6348-11eb-9e3c-bf206d623e98.png)

**Comment by renqiukai** [comment]
command_output = subprocess.run(["netsh", "wlan", "show", "profiles"], capture_output = True).stdout.decode(**"gb2312"**)

**Comment by Kokojuice2** [comment]
Did what you suggested, received this error. 

![image](https://user-images.githubusercontent.com/61834672/107129119-6e195f00-68c3-11eb-8757-a85f5c027cac.png)

What can we do to fix this? 
Thanks in advance!

**Comment by saurabhkingp** [comment]
![image](https://user-images.githubusercontent.com/72145932/110466238-85827c80-80fb-11eb-9ea6-89722a96f870.png)

I am getting the same error.
Plzz tell us how to resolve this

**Comment by dawidvanstraaten** [comment]
> ![image](https://user-images.githubusercontent.com/72145932/110466238-85827c80-80fb-11eb-9ea6-89722a96f870.png)
> 
> I am getting the same error.
> Plzz tell us how to resolve this

Try the following change (Add the 'utf-8', 'ignore' arguments to decode methods in the script):

command_output = subprocess.run(["netsh", "wlan", "show", "profiles"], capture_output = True).stdout.decode('utf-8', 'ignore')

**Comment by saurabhkingp** [comment]
> > ![image](https://user-images.githubusercontent.com/72145932/110466238-85827c80-80fb-11eb-9ea6-89722a96f870.png)
> > I am getting the same error.
> > Plzz tell us how to resolve this
> 
> Try the following change (Add the 'utf-8', 'ignore' arguments to decode methods in the script):
> 
> command_output = subprocess.run(["netsh", "wlan", "show", "profiles"], capture_output = True).stdout.decode('utf-8', 'ignore')

Not working it says TabError: inconsistent use of tabs and spaces in indentation.
IDK why but I had tried many steps but nothing is working for me.

**Comment by daman9999** [comment]
replace stdout.decode() with stdout.decode("cp1252") it will work

**Comment by davidbombal** [comment]
Thanks @daman9999
