### ISSUE TITLE
File format not supported! Error on Kali Linux

### ISSUE THREAD

**Issue by lazengann86** [davidbombal/red-python-scripts#34]
running the script I get the "File format not supported!" error with both File and Terminal options. The images are .JPG and/or .PNG

Anyone else getting this error?

**Comment by davidbombal** [comment]
.PNG requires a different implementation. Only .jpg, and .tiff are supported for the current script. I will update it to add .png, and .heic formats. But the current script is clear on the support.

**Comment by lazengann86** [comment]
I see, but then why would I still get the error with .JPG files?
