### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 698: invalid start byte

### ISSUE THREAD

**Issue by ashifpm** [davidbombal/red-python-scripts#4]
Traceback (most recent call last):
  File "C:\Users\Ashif\Desktop\red-python-scripts-main\windows10-wifi.py", line 43, in <module>
    profile_info = subprocess.run(["netsh", "wlan", "show", "profile", name], capture_output = True).stdout.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 698: invalid start byte

**Comment by daman9999** [comment]
you are working on windows machine since utf-8 is wrong encoding for that , utf-8 is default encoding for this if you write stdout.decode() instead replace it with stdout.decode("cp1252") it will work ;)

**Comment by davidbombal** [comment]
Thanks @daman9999

**Comment by TonyLeeIT** [comment]
> you are working on windows machine since utf-8 is wrong encoding for that , utf-8 is default encoding for this if you write stdout.decode() instead replace it with stdout.decode("cp1252") it will work ;)

tks  so much

**Comment by luccavp12** [comment]
> you are working on windows machine since utf-8 is wrong encoding for that , utf-8 is default encoding for this if you write stdout.decode() instead replace it with stdout.decode("cp1252") it will work ;)

Your idea helped fix my random issue. Thank you!
