### ISSUE TITLE
Wifi controller

### ISSUE THREAD

**Issue by rougixxx** [davidbombal/red-python-scripts#42]
Hi. when I execute the python script it will exit directly after showing the user interface (david bombal name and details) and the script tells me to connect to a wifi controller and try again.I am have a wifi adapter supports monitor mode and I tried the script in Manjaro linux distro.
Note: I also tried the script in kali linux and it worked perfectly
![davidissue](https://user-images.githubusercontent.com/81870072/192105593-ad2fe1d8-7a7b-4358-be9e-a7e0ae216993.png)

**Comment by shiva9108** [comment]
Good Thing! It Worked!

**Comment by rougixxx** [comment]
Sorry for disturbing
