### ISSUE TITLE
Repostories of pip

### ISSUE THREAD

**Issue by deadpool-hacker07** [davidbombal/red-python-scripts#5]
File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

**Comment by DobroAlex** [comment]
@deadpool-hacker07  , what OS are you using? It seems to be a Linux problem with OS packages

**Comment by davidbombal** [comment]
Dear @deadpool-hacker07 can you please let me know which script you're trying to run, also please supply more information on your operating system.
